export const POSTS_SORT_KEYS = {
    BY_MIN_ID: "BY_MIN_ID",
    BY_MAX_ID: "BY_MAX_ID",
    BY_POST_NAME: "BY_POST_NAME",
    BY_POST_AUTHOR: "BY_POST_AUTHOR",
    BY_POST_FAVORITES: "BY_POST_FAVORITES"
}